#ifndef CACHE_BRUTE_FORCE
#define CACHE_BUTE_FORCE

#define NUMREG 16
#define DIVINT 16
#define DIVINDM 32

#define MEDIAN_WIDTH    5
#define MEDIAN_THREADS  256

#define MEAN_NUM_BLOCKS  512
#define MEAN_NUM_THREADS 256 
#endif
